name: "Validating GeekoDoc"

on: push

jobs:
  validate:
    name: "Test GeekoDoc"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Checkout rnginline
        uses: actions/checkout@v3
        with:
          repository: h4l/rnginline
          path: rnginline

      - name: Install dependencies
        run: |
          sudo apt-get install libxml2-utils trang jing python3-setuptools python3-wheel

      - name: Preparing rnginline

        run: |
          (cd rnginline; sudo pip3 install -e .)
          whereis rnginline

      - name: Building GeekoDoc
        run: ./build.sh -vvv

      - name: Testing GeekoDoc
        run:  ./tests/run-tests.sh
